### ISSUE TITLE
Dash Sublime Settings

### ISSUE THREAD

**Issue by petergeller** [farcaller/DashDoc#26]
i read the article about https://sublime.wbond.net/packages/DashDoc 
I setup everything and it worked as described, but i have a problem to setup the individual syntax to docket setting.

At the moment i override the html docset in DashDoc.sublime-settings - DashDock  like that to keep your default settings in the file.

```
    "HTML"                  : ["html","css","ee","foundation"], // "svg", "css", "bootstrap", "foundation", "javascript", "jquery", "jqueryui", "jquerym", "angularjs", "backbone", "marionette", "meteor", "moo", "prototype", "ember", "lodash", "underscore", "sencha", "extjs", "knockout", "zepto", "cordova", "phonegap", "yui"
```

because it didn't worked for me to override this settings in my xxx.sublime-project like that

```
{
    "folders":
    [
        {
            "path": "/Users/pog/webserver/project_xx"
        }
    ],
    "settings": {
      "syntax_docset_map": {
        "HTML" : ["html","css","ee","foundation"]
      }
    }
}
```

everytime i tried it before without to manipulate your default settings it didn't worked out for me.
Any ideas why?

I also tried out to override the user settings of DashDock but that also didn't work.

Any help with that would be great.

Best Peter

**Comment by farcaller** [comment]
No updates on this one, so I'm closing it as obsolete.
