### ISSUE TITLE
Provide a better option for default dash hotkey

### ISSUE THREAD

**Issue by farcaller** [farcaller/DashDoc#29]
Tracking bug for issue in #28.

**Comment by ernestyao** [comment]
I hope to change the default key map or let user setting replace default one would be much helpful. Ctrl+H is DEL in OS X. When I don't want to move to Delete key(mostly in HHKB keyboard), I switch to this combination and got confused in dashdoc.

**Comment by kylestev** [comment]
`cmd` + `` ` `` is what I use. The upward-left movement isn't completely ideal, but it feels more natural than `ctrl`+`h`

**Comment by ernestyao** [comment]
But how could I configure the plugin to ignore `ctrl+h` ?

**Comment by kylestev** [comment]
Huh. You have a good point -- pressing ctrl + h after defining a key
binding in user settings for the package still results in opening dash...
That's odd.

**Comment by orcinus** [comment]
I'm a little confused here.
Isn't Ctrl+H on Macs a left delete?

How do i invoke DashDoc at all?
Am i missing something?

**Comment by zhaozechou** [comment]
{
        "button": "button1", 
        "count": 1, 
        "modifiers": ["alt"],
        "press_command": "drag_select",
        "command": "dash_doc"
    }
this will be consistent with XCode

**Comment by deathaxe** [comment]
The keybinding ctrl+h is used to open the replace panel by the default.sublime-package. You must not overwrite default key bindings, if you don't intend to replace a default function by a better one.

**Comment by farcaller** [comment]
This is fixed in 2.0 now.
