### ISSUE TITLE
Issues with looking up correct language.

### ISSUE THREAD

**Issue by iamthesiz** [farcaller/DashDoc#32]
So basically whenever I have my cursor over a function, I hit my keybinding to do the quick dash-lookup and instead of taking me to the PHP docs, it seems to be taking me to  either HTML5 or Bootstrap.  Any ideas what's causing this?

**Comment by joshmfrankel** [comment]
I am also experiencing a similiar issue with a ruby file. When I try the keyboard shortcut over the ruby keyword "map" it takes me instead to Javascript as the first result. File has the ```.rb``` extension. In the bottom right corner of Sublime it is listed as Ruby. I've tried using the above mentioned command in the Sublime console.
```
view.settings().get('syntax')
```
Which results in following output ```Packages/Ruby/Ruby.tmLanguage```. 

I did notice inside the Dash application that by going to ```Preferences/DocSets``` and changing the priority order of your docsets to match the languages you work the most in, it can help reduce the amount of times you are taken to the wrong programming language documentation. Is there a way for it to just go to my Ruby docset first when on a Ruby file?
