### ISSUE TITLE
Call Dash without activating it

### ISSUE THREAD

**Issue by Kapeli** [farcaller/DashDoc#36]
DashDoc calls Dash by opening a `dash-plugin://` URL. The problem is that the system forces Dash to become active when this URL is opened.

Currently, this is not an issue. However, a future update of Dash will add support for iOS remotes. While an iOS remote is connected, extensions are redirected to it directly and Dash on OS X is not shown at all. Unfortunately there's no way for me to prevent the system from activating Dash when you open the `dash-plugin://` URL.

Instead of doing this:
```
open dash-plugin://query
```

Can you do this?
```
open -g dash-plugin://query
```

The `-g` causes Dash to not get activated if it does not want to and the user experience is a lot better as the active app does not lose focus anymore.

It is safe to make this change as soon as possible (no need to wait for a Dash update), as the current version of Dash already knows to activate itself if it needs to.

**Comment by Kapeli** [comment]
Thanks for the quick fix! :+1:

**Comment by farcaller** [comment]
> add support for iOS remotes

you got me motivated :smiley:
