### ISSUE TITLE
Have Dash snippets available in SublimeText

### ISSUE THREAD

**Issue by phdoerfler** [farcaller/DashDoc#38]
As an avid user of Dash snippets I would like to have them available in SublimeText in order to save me from manually switing to Dash, selecting the snippet in question there with the mouse, copying it, returning back to SublimeText in order to finally pasting it and then manually filling the gaps.

Ideally the Dash snippets appear in the list of snippets already available in SublimeText (as invoked by Tools: Snippets...)

**Comment by Kapeli** [comment]
Fwiw, you can currently expand in Sublime Text directly using snippet abbreviations. See https://kapeli.com/dash_guide#snippets.

**Comment by farcaller** [comment]
as @Kapeli noted, this is a built-in feature of Dash, I don't think a tighter level of integration is really needed as Dash abbreviations work perfectly with ST.
