### ISSUE TITLE
Not in Package control

### ISSUE THREAD

**Issue by montogeek** [farcaller/DashDoc#40]
I cant find this package in Package control, I am trying with `Dash Doc`.

**Comment by farcaller** [comment]
Are you running OS X?

**Comment by montogeek** [comment]
Yes, and ST3

**Comment by farcaller** [comment]
Can you verify now please?

**Comment by montogeek** [comment]
Yes, fixed :)
Thanks!

**Comment by brandonarbini** [comment]
Is it missing again? I'm on OS X, ST3 (3083).

**Comment by farcaller** [comment]
No, literally nothing changed since May. Those all are package control issues, not ours.

**Comment by brandonarbini** [comment]
Ok, cool. Thanks. Seems to be fixed for me now.

**Comment by baweaver** [comment]
If you find that the package is missing for some reason, use: `Package Control: Advanced Install Package`

It takes in a CSV list of package names and installs them. Worked for me whenever dashdoc was suspiciously missing due to some shenanigans.
