### ISSUE TITLE
Alfred search immediately overrides the tab search

### ISSUE THREAD

**Issue by katerlouis** [farcaller/DashDoc#45]
I almost exclusively use Dash with Alfred.

When I type in a command the activatd tab in Dash gets overwritten with the new search.
This is bugging me for years now!

Suggestions:

1) Searching with Alfred opens a new tab and searchs there (Don't like this one)

2) Alfred doesn't search inside the Dash-App until I hit Enter; It then would always open a new Tab, unless I press CMD+Enter.

What do you say?

**Comment by farcaller** [comment]
I say – I have no idea how Dash integration in Alfred works, this repo integrates it with Sublime Text. Maybe you look for https://github.com/Kapeli/Dash-Alfred-Workflow ?

**Comment by katerlouis** [comment]
I'm sorry; don't know how I ended up in this repo– thought I was on Kapeli.
Have a good one.
