### ISSUE TITLE
Recent versions not appearing in Package Control

### ISSUE THREAD

**Issue by mnkhouri** [farcaller/DashDoc#52]
The latest version available in Package Control is 1.6.0 (see [here](https://packagecontrol.io/packages/DashDoc)). 

It looks like Package Control requires version numbers with the format `x.y.z`, not just `x.y` (see [here](https://packagecontrol.io/docs/submitting_a_package#Step_4))

**Comment by farcaller** [comment]
Huh.

Thanks for the notice, I've re-tagged everything even more semantically now.
