### ISSUE TITLE
After upgrading to the 2.4.0 ctrl+h stopped working

### ISSUE THREAD

**Issue by jacek-adamek** [farcaller/DashDoc#53]
After upgrading to the version 2.4.0 `ctrl+h` does not work anymore. I suppose that's because of deleting `*.sublime-keymap` files.

**Comment by farcaller** [comment]
Yep, it was removed long ago. Here's the doc that you're looking for:

https://github.com/farcaller/DashDoc/blob/master/messages/2.0.txt
