### ISSUE TITLE
Not working with latest sublime Version 3, Build 3143

### ISSUE THREAD

**Issue by Jayiitb** [farcaller/DashDoc#55]
Missing Default key bindings.

**Comment by triat** [comment]
So actually the fix found for that is to add this line in your own key binding (Preferences -> key bindings)

`{ "keys": ["ctrl+h"], "command": "dash_doc"}`

**Comment by farcaller** [comment]
It's intentional and was mentioned in the 2.0 upgrade notes, see https://github.com/farcaller/DashDoc/issues/29 for context.

I've updated the readme to reflect this.

**Comment by Jayiitb** [comment]
@farcaller @triat - Thanks for the help. 
I was missing this piece henceforth using Atom. Now I can use sublime peacefully.

Cheers! 👍
