### ISSUE TITLE
Hotkey for opening Dash in Sublime Text

### ISSUE THREAD

**Issue by hjmf1954** [farcaller/DashDoc#57]
The Hotkey Ctrl-H does not work anymore in the new version of Sublime Text (Version 3.0 Build 3143) in OSX.

**Comment by farcaller** [comment]
Dup of https://github.com/farcaller/DashDoc/issues/29, see the [readme](https://github.com/farcaller/DashDoc/blob/master/README.md) for details.

**Comment by hjmf1954** [comment]
Thx for your quick answer. I have a suggestion.
This issue occurs after an update of Sublime Text and/or Dash. Maybe the user gets a warning that he/she has to add an new hotkey in the update of Dash.

**Comment by farcaller** [comment]
there is a warning: https://github.com/farcaller/DashDoc/blob/master/messages/2.0.txt I'm not sure if it's not showing up or something else is broken though.

**Comment by jinsanity07git** [comment]
Add the following code to the keymapfile
```
[{ "keys": [" ctrl+h"], "command": "dash_doc",
                           "args": { "flip_syntax_sensitive": true } }]
```
![image](https://user-images.githubusercontent.com/31701385/73614944-8e844e80-45c9-11ea-9d54-d35d44b92c88.png)
