### ISSUE TITLE
Page not updating

### ISSUE THREAD

**Issue by ocket8888** [farcaller/DashDoc#61]
I'm on a 2017 Macbook Pro, running macOS Sierra 10.12.6 with the latest version of Dash, and I'm having this issue:

it doesn't work.

I've used this extension before on Windows and Linux, where it works flawlessly, but on macOS, when I run the `dash_doc` command on a selected bit of text, absolutely nothing will happen if I already have Dash open. If I close Dash and try again, it'll open dash... but only to whatever page I happened to be looking at last time I closed it; it's not searching for what I typed.

I'm new to mac, so it's possible that I just don't know what I'm doing, but I've tried running through the command palette and binding a key, and frankly I don't know what I could be missing.

**Comment by alextegelid** [comment]
I second this. I've been using DashDoc och Mac for a long time (a couple of years at least) but yesterday it stopped working. All the symptoms that @ocket8888 describe is true for me too.

I'm using Sublime Text 3, build 3143 on a MacBook Pro (Retina, 13-inch, Early 2015)

**Comment by alisspers** [comment]
See the other issue created a few days back, seems to be a fix coming: https://github.com/farcaller/DashDoc/issues/59

**Comment by j9ac9k** [comment]
Sorry guys, in my attempt to make it work on Linux, I broke it for macOS; I submitted a pull request for a macOS fix, in the meantime, you can see my post here: https://github.com/farcaller/DashDoc/issues/59 detailing how to make the fix yourself.

**Comment by farcaller** [comment]
I believe it's fixed now, in 2.6.0 release.
