### ISSUE TITLE
Not working on Mac 10.14.5 ST3

### ISSUE THREAD

**Issue by mgarcia96** [farcaller/DashDoc#64]
{ "keys": ["ctrl+h"], "command": "dash_doc"},

With keys or with the menu doesn't work

**Comment by AkhterAli** [comment]
Although this is correct per the docs, I found out that this would work

```
[{ "keys": ["super+h"], "command": "dash_doc", "args": {"flip_syntax_sensitive": false}}]
```

Basically the bindings have to enclosed in an array as well.
